<!--Footer inc for every page-->
<footer>
        <section class="footer">
            <h4>About</h4>
            <p>This is a website for searching the WiFi hot spots in Brisbane.</p>
        </section>
        <section class="footer">
            <img src="images/logo_1.png" width="100px" alt="logo" />
            <p>Copyright © 2015 Kian Zhu</p>
        </section>
        <section class="footer">
            <h4>Categorise</h4>
            <ul>
                <!--Categorise links in a list-->
                <li><a href="index.php">Home</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="admin.php">Upload csv</a></li>
            </ul>
        </section>
    </footer>
